### PR TITLE
tried to put some authorizations

### PR DESCRIPTION
**Pull request by gsysaath**
Created all the policies for the models, changed a few things in the recipe and cookbook controller we did together.
Tried to do all the controllers + policies and i just allowed the recipes index method.
NOT SURE ABOUT THE TODAY METHOD IN WEEK

### CODE REVIEW

**Comment by gsysaath** [comment]
Screenshot 2020-11-24 at 00 56 44
uniqueness with name if they have the same user

**Comment by gsysaath** [comment]
Screenshot 2020-11-24 at 00 53 51
Name has to be ALPHANUMERIC

You can see ROLLBACK in the screenshot

**Comment by gsysaath** [comment]
Added length in cookbook model
Added all the validations in the recipe model

**Review by shakshouka — APPROVED** [review]
Great job mate !! 👍

**Pull request merged**
